sudo: required
dist: trusty
services:
  - docker
language: python
install:
  - docker build -t stevenpollack/conda-r .
script:
  - docker run -P --name postgres -d jamesbrink/postgres
  - sudo docker run -it --link postgres:db stevenpollack/conda-r env | grep DB 
  - docker run -it --link postgres:db stevenpollack/conda-r Rscript test_Rpostgres.R
