sudo: required
dist: trusty
services:
  - docker
language: python
install:
  - docker build -t conda-r .
script:
  - docker run -P --name postgres jamesbrink/postgres
  - docker run -it --link postgres:db conda-r Rscript test_Rpostgres.R
