sudo: required
dist: trusty
services:
  - docker
language: python
install:
  - docker build -t stevenpollack/conda-r .
script:
  - sudo docker run -P --name postgres -e USER=travis -e PASSWORD=swordfish -d jamesbrink/postgres
  - sudo docker run -it --link postgres:db stevenpollack/conda-r env | grep DB 
  - sudo docker run -it --link postgres:db stevenpollack/conda-r Rscript test_Rpostgres.R
